### ISSUE TITLE
Security Concern: Unobfuscated Confidential Information in Trace api.v2.auth

### ISSUE THREAD

**Issue by s4ds5ms6i** [snapp-incubator/soteria#94]
In the current implementation of trace api.v2.auth, sensitive information such as JWT tokens and usernames are being recorded in an unmasked form within the respective token and username tags. Additionally, a tag labeled password is also being logged, which appears to store sensitive password data.

To address this issue, I propose the introduction of a test mode (if one does not already exist). In test mode, the current behavior can remain unchanged for debugging purposes. However, outside of test conditions, confidential information should be obfuscated. For instance, passwords could be hashed with a salt, and parts of tokens could be masked (e.g., replaced with *).

This will ensure sensitive data is protected while still allowing for useful tracing in non-production environments.

![Screenshot 2024-10-13 at 23 07 01](https://github.com/user-attachments/assets/a4bcdc6e-701e-4df8-ab22-b8d70ba267c3)

**Comment by 1995parham** [comment]
Hi Shahram jan, you are completely right. The data is exposed from our tracing system, which is internal but shared between company. I think we can completely remove these tags.
